### ISSUE TITLE
Add a `.clang-format` file in the top-most directory

### ISSUE THREAD

**Issue by xoox** [lagadic/visp#206]
There is already a [ViSP coding style guideline](https://github.com/lagadic/visp/wiki/coding-style-guideline). But codes in the repository is not as consistency as expected.
Some utilities exist to help to enhance coding formats, such as [clang-tidy](http://clang.llvm.org/extra/clang-tidy/) and [clang-format](http://clang.llvm.org/docs/ClangFormat.html).

Would you please add a `.clang-format` file in the top-most directory, which will ensure the coding format to some extents. For example, the following format are used with changes in #205.

```
$ cat .clang-format
```

```yaml
---
Language: Cpp
BasedOnStyle: LLVM
BreakBeforeBraces: Linux
ColumnLimit: 78
ConstructorInitializerIndentWidth: 2
...
```
This configuration has been tested with clang-format-3.9 and clang-format-4.0, and may be compatible with versions >=3.8
```
$ clang-format -i some_source.cpp
```
Wish a `.clang-format` file will be helpful to all developers.
