### ISSUE TITLE
April Tags and depth image.

### ISSUE THREAD

**Issue by jmirabel** [lagadic/visp#668]
Dear ViSP developpers,

In our project, we use the AprilTag wrapper of ViSP (v3.2.0) to get the pose of some AprilTag with respect to the camera. From time to time, the pose estimation is stuck in a local minima due to an ambiguity when the tag is close to being orthogonal to the camera normal. I tried LAGRANGE_VIRTUAL_VS and DEMENTHON_VIRTUAL_VS.

Is there any solution to this issue in ViSP ?
One way of removing the ambiguity is to use the depth information. Is it possible to provide depth information to ViSP ?

Can I expect the method HOMOGRAPHY_VIRTUAL_VS in ViSP 3.2.1 to behave better ?

**Comment by fspindle** [comment]
The best would be to attach and image with the tag and the corresponding camera parameters that produce the issue. I could then investigate...

**Comment by jmirabel** [comment]
Thank for your quick reply. You can find the image here: https://github.com/agimus/agimus-vision/issues/5

The camera parameters are read from a ROS topic and converted into ViSP camera parameters (https://github.com/agimus/agimus-vision/blob/122c40daf4a0df3c05fe113412bb82220cba1f65/src/tracker_object/node.cpp#L134). The topic contains:
```yaml
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.1342682457423161, -0.185169495024767, 0.008633872454571442, -0.006708097638208048, 0.0]
K: [606.927873247237, 0.0, 317.0942192234208, 0.0, 608.7315077548897, 255.8098355816944, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [625.0511474609375, 0.0, 313.3595109513262, 0.0, 0.0, 626.72314453125, 259.4014303951117, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
